BASE16_SHELL=$HOME/.dotfiles/base16-shell/
[[ -e $BASE16_SHELL/profile_helper.sh ]] && eval "$($BASE16_SHELL/profile_helper.sh)"

POWERLEVEL9K_MODE="nerdfont-complete"
DEFAULT_USER="$USER"
POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(context dir_writable dir virtualenv vcs)
POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(status command_execution_time background_jobs vi_mode load ram)
POWERLEVEL9K_SHORTEN_STRATEGY=truncate_from_right
POWERLEVEL9K_SHORTEN_DIR_LENGTH=3
POWERLEVEL9K_VCS_GIT_HOOKS=(vcs-detect-changes git-untracked git-aheadbehind git-stash git-tagname)
POWERLEVEL9K_STATUS_VERBOSE=false
POWERLEVEL9K_HOME_SUB_ICON='\UF015'
POWERLEVEL9K_PYTHON_ICON='\UE73C'
POWERLEVEL9K_VCS_GIT_ICON='\UF113'
POWERLEVEL9K_HOME_FOLDER_ABBREVIATION=''
POWERLEVEL9K_FOLDER_ICON=''
POWERLEVEL9K_BACKGROUND_JOBS_ICON='\UF013'
POWERLEVEL9K_VCS_GIT_GITHUB_ICON='\UE709'

source ~/.dotfiles/powerlevel9k/powerlevel9k.zsh-theme
POWERLEVEL9K_VI_MODE_INSERT_BACKGROUND='blue'
POWERLEVEL9K_VI_MODE_INSERT_FOREGROUND=$DEFAULT_COLOR
POWERLEVEL9K_VI_MODE_NORMAL_BACKGROUND='blue'
POWERLEVEL9K_VI_MODE_NORMAL_FOREGROUND=$DEFAULT_COLOR
