BASE16_SHELL=$HOME/.dotfiles/base16-shell/
[[ -e $BASE16_SHELL/profile_helper.sh ]] && eval "$($BASE16_SHELL/profile_helper.sh)"

POWERLEVEL9K_MODE="nerdfont-complete"
DEFAULT_USER="$USER"
POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(context dir_writable dir virtualenv vcs)
POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(status command_execution_time background_jobs vi_mode load ram)
POWERLEVEL9K_SHORTEN_STRATEGY=truncate_middle
POWERLEVEL9K_SHORTEN_DIR_LENGTH=3
POWERLEVEL9K_VCS_GIT_HOOKS=(vcs-detect-changes git-untracked git-aheadbehind git-stash git-tagname)
POWERLEVEL9K_DIR_DEFAULT_BACKGROUND='default'
POWERLEVEL9K_DIR_DEFAULT_FOREGROUND='blue'
POWERLEVEL9K_DIR_HOME_BACKGROUND='default'
POWERLEVEL9K_DIR_HOME_FOREGROUND='blue'
POWERLEVEL9K_DIR_HOME_SUBFOLDER_BACKGROUND='default'
POWERLEVEL9K_DIR_HOME_SUBFOLDER_FOREGROUND='blue'
POWERLEVEL9K_DIR_WRITABLE_FORBIDDEN_BACKGROUND='default'
POWERLEVEL9K_DIR_WRITABLE_FORBIDDEN_FOREGROUND='red'
POWERLEVEL9K_VCS_BACKGROUND='default'
POWERLEVEL9K_VCS_FOREGROUND='green'
POWERLEVEL9K_VCS_CLEAN_BACKGROUND='default'
POWERLEVEL9K_VCS_CLEAN_FOREGROUND='green'
POWERLEVEL9K_VCS_MODIFIED_BACKGROUND='default'
POWERLEVEL9K_VCS_MODIFIED_FOREGROUND='green'
POWERLEVEL9K_VCS_UNTRACKED_BACKGROUND='default'
POWERLEVEL9K_VCS_UNTRACKED_FOREGROUND='green'
POWERLEVEL9K_VIRTUALENV_BACKGROUND='default'
POWERLEVEL9K_VIRTUALENV_FOREGROUND='white'
POWERLEVEL9K_STATUS_ERROR_BACKGROUND='default'
POWERLEVEL9K_BACKGROUND_JOBS_BACKGROUND='default'
POWERLEVEL9K_VI_MODE_INSERT_BACKGROUND='default'
POWERLEVEL9K_VI_MODE_NORMAL_BACKGROUND='default'
POWERLEVEL9K_LOAD_NORMAL_BACKGROUND='default'
POWERLEVEL9K_LOAD_NORMAL_FOREGROUND='green'
POWERLEVEL9K_LOAD_WARNING_BACKGROUND='default'
POWERLEVEL9K_LOAD_WARNING_FOREGROUND='yellow'
POWERLEVEL9K_LOAD_CRITICAL_BACKGROUND='default'
POWERLEVEL9K_LOAD_CRITICAL_FOREGROUND='red'
POWERLEVEL9K_RAM_BACKGROUND='default'
POWERLEVEL9K_RAM_FOREGROUND='blue'
POWERLEVEL9K_STATUS_VERBOSE=false
POWERLEVEL9K_PYTHON_ICON='\UE73C'
POWERLEVEL9K_VCS_GIT_ICON='\UF113'
POWERLEVEL9K_HOME_FOLDER_ABBREVIATION=''
POWERLEVEL9K_FOLDER_ICON=''
POWERLEVEL9K_BACKGROUND_JOBS_ICON='\UF013'
POWERLEVEL9K_VCS_GIT_GITHUB_ICON='\UE709'

source ~/.dotfiles/powerlevel9k/powerlevel9k.zsh-theme

POWERLEVEL9K_HOME_SUB_ICON=$(print_icon 'HOME_ICON')
POWERLEVEL9K_VCS_REMOTE_BRANCH_ICON=" $(print_icon 'VCS_REMOTE_BRANCH_ICON')"
POWERLEVEL9K_LEFT_SEGMENT_SEPARATOR=$(print_icon 'LEFT_SUBSEGMENT_SEPARATOR')
POWERLEVEL9K_RIGHT_SEGMENT_SEPARATOR=$(print_icon 'RIGHT_SUBSEGMENT_SEPARATOR')
